### ISSUE TITLE
Update list of categories 

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#10]
Add the following categories to the category table

1. Report a matter/incident
2. Report a suspected case of COVID-19
3. Request help - Access or delivery of essential grocery supplies or medicines
4. Request help - Financial assistance towards essential grocery supplies or medicines
5. Request help - Samurdhi allowances 
6. Request help - Elders allowances 
7. Request help - Temporary allowances 
8. Request help - Other allowances
9. Request help - Pensioners 
10. Request help - Farming pensioners 
11. Sri Lankan citizen living overseas - Help wanted in overseas country 
12. Sri Lankan citizen living overseas - Assistance for family members in SL 
13. Expatriates/ Residents of Sri Lanka w/ foreign citizenship/ Diplomatic embassies
14. Tourist 
15. Government organization
16. Other 

Find the possible category types and add them as well

**Comment by MrClemRkz** [comment]
completed.

**Comment by nshamit** [comment]
Report a matter/incident
Report a suspected case of COVID-19
Request help - Access or delivery of essential grocery supplies or medicines
Request help - Financial assistance towards essential grocery supplies or medicines
Request help - Samurdhi allowances
Request help - Elders allowances
Request help - Temporary allowances
Request help - Other allowances
Request help - Pensioners
Request help - Farming pensioners
Sri Lankan citizen living overseas - Help wanted in overseas country
Sri Lankan citizen living overseas - Assistance for family members in SL
Expatriates/ Residents of Sri Lanka w/ foreign citizenship/ Diplomatic embassies
Tourist
Government organization
Other

**Comment by MrClemRkz** [comment]
completed
