### ISSUE TITLE
Manager should be able to verify any record regardless of who is assigned to the request

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#101]
Currently, if the issue is assigned to the coordinator, it cannot be verified by a manager UNLESS the manager assigns himself. 

The manager should be able to verify any incident assigned to any other role.

**Comment by MrClemRkz** [comment]
this is achived by the process where he can assign the request to himself and then verify it. basic condition set it, whoever taking actiong on particular request must be assigned to it.

**Comment by MrClemRkz** [comment]
create a new permission for this.

**Comment by MrClemRkz** [comment]
new permisson created as 'CAN_ACTION_OVER_CURRENT_ASSIGNEE'
