### ISSUE TITLE
Linking action pending officers or organizations to the comment trail section w/ the action details 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#133]
Where an officer/ org needs to take action, they will be listed in the action pending side. 
If you click on the name they should be directed to the section in the comment trail where the action details are 

- [x] backend
- [ ] frontend

**Comment by MrClemRkz** [comment]
upon click on 'assisgn to' list will show assigned list if there is more than one.

**Comment by MrClemRkz** [comment]
new issue created for left over work - #203
