### ISSUE TITLE
Organization can close an issue by themselves and the PS will receive a system notification about the issue closure.  

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#134]
Organization can close an issue by themselves and the PS will receive a system notification about the issue closure.  

Previously, for the EC, the EC had to close all issues that were assigned to others.

**Comment by ManZzup** [comment]
Fixed in https://github.com/LSFLK/request-management/commit/ed1aeeb44ca704c55d8aad7a5f6b5cb12ae09f00
