### ISSUE TITLE
Daily Summary Report - No. of requests closed by organization  

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#136]
Title: Daily Summary Report - No. of requests closed by organization 

- Bold Total 
- Include “No. of issues open” underneath total
- Under organization, they could list the division so reports can maintain the same format and change the headings/ field titles. Instead of Category, you can use Organization 

- [x] backend

**Comment by YujithIsura** [comment]
frontend completed

**Comment by MrClemRkz** [comment]
backend completed. value passed by the variable name = "totalOpenedCount"
