### ISSUE TITLE
Guest user - Clicking on behalf of someone takes the user to a field in the middle of the form. 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#139]
Citizen /Guest user - create request. 
When I click on behalf of someone else, I am directed to the field line which says description/landmarks instead of to the top of the form. 

![Screen Shot 2020-04-30 at 10 33 54](https://user-images.githubusercontent.com/44461004/80673964-3e386200-8ace-11ea-90e8-956c5cbe1917.jpg)

Also, when you click on the button **Create another Complaint,** the user is directed to the same field at the top of a new form.

**Comment by MrClemRkz** [comment]
completed.
