### ISSUE TITLE
Make drop downs user friendly and dynamic - when you type in a letter, it should narrow the drop down choices 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#141]
When you open a drop down and type in a letter, it should narrow down your choices for you. 
For example, in a full list of GN's, if I type in B, i should get only the B GNs. 

![Screen Shot 2020-04-30 at 11 01 43](https://user-images.githubusercontent.com/44461004/80675476-2b279100-8ad2-11ea-87e5-070c63bc947f.jpg)

**Comment by MrClemRkz** [comment]
this is fixed.
