### ISSUE TITLE
Review and archive page changes 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#144]
- [x] Add priority column to the review and archive pages. It is available in the advanced search, filter section, but not the review screen/archive page. 

- [x] Improve the PDF informal report.

- lessen the space used for description. 
- increase space for the category
- change the title column name to "Mode of receipt" 

![Screen Shot 2020-04-30 at 20 46 56](https://user-images.githubusercontent.com/44461004/80727782-c1d06e00-8b23-11ea-830a-53e0ed5cf031.jpg)

**Comment by nshamit** [comment]
- [ ] 



- [ ] Archive section allows a user to filter status by new, verified, action pending.

in the archive section, there are only issues that are closed or invalidated.

![Screen Shot 2020-04-30 at 12 50 59](https://user-images.githubusercontent.com/44461004/80940668-17479c00-8dfe-11ea-9bfd-3503331e83e7.jpg)

should only allow filter by closed or invalidated

**Comment by umayangag** [comment]
**RE: should only allow filter by closed or invalidated** :- The search form used is common to both review page and archive page. The status cannot be changed as such without major changes. There is not invalidated state. Close state is available and can be enabled.

**Comment by MrClemRkz** [comment]
> * [x]  Add priority column to the review and archive pages. It is available in the advanced search, filter section, but not the review screen/archive page.
> * [x]  Improve the PDF informal report.
> * lessen the space used for description.
> * increase space for the category
> * change the title column name to "Mode of receipt"
> 
> ![Screen Shot 2020-04-30 at 20 46 56](https://user-images.githubusercontent.com/44461004/80727782-c1d06e00-8b23-11ea-830a-53e0ed5cf031.jpg)

mode of receipt value fix added.

**Comment by MrClemRkz** [comment]
> * [x]  Archive section allows a user to filter status by new, verified, action pending.
> 
> in the archive section, there are only issues that are closed or invalidated.
> 
> ![Screen Shot 2020-04-30 at 12 50 59](https://user-images.githubusercontent.com/44461004/80940668-17479c00-8dfe-11ea-9bfd-3503331e83e7.jpg)
> 
> should only allow filter by closed or invalidated

fixed.
