### ISSUE TITLE
Internal user: Create request form. Mobile number is mandatory, no asterisk on the field

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#153]
Mobile number is made mandatory through validation. 
We need to include an asterisk* to denote that the field is mandatory. Mobile number will be needed to resolve issues directly w/ the person who needs help. 

![Screen Shot 2020-04-30 at 16 37 01](https://user-images.githubusercontent.com/44461004/80703966-5ecddf80-8b01-11ea-8847-564228c2925b.jpg)

**Comment by YujithIsura** [comment]
this will be fixed with new update
