### ISSUE TITLE
Dashboards (Grafana)

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#162]
General
- [ ] Total no. of requests open
- [ ] Total no. of requests closed each day
- [ ] Total no. of requests open
- [ ] Total no. of incidents by priority 
- [ ] Total no. of incidents by district 

**Category** 
- [ ] total number of requests, by category (assigned)

- [ ] Daily - total number of requests closed, by category

- [ ] Total no. of requests (by category) open after 3 days, 7 days, 14 days, 21 days, 28 days, 1+ months.  

**Organization**
- [ ] total number of requests, by organization (assigned)

- [ ] Daily - total number of requests closed, by organization

- [ ] Total no. of requests (by organization) open after 3 days, 7 days, 14 days, 21 days, 28 days, 1+ months.

**Comment by MrClemRkz** [comment]
invalidated.
