### ISSUE TITLE
Email notifications - backend

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#17]
Develop end-points for following email sending options 

- [x] To citizen upon creation of request to acknowledge receipt
- [x] To citizen upon closure with the outcome 
- [x] To an organization that has been delegated/assigned a request 
- [ ] Integrate gov mail server

**Comment by aijdissanayake** [comment]
Removed the task " To citizen requesting more information is required to proceed " from the task list since it has a workflow dependency not related to email notification. @MrClemRkz Better to create a separate issue for that and move it to the Phase 2?

**Comment by MrClemRkz** [comment]
created new issue for: **Integrate gov mail server** https://github.com/LSFLK/request-management/issues/100
