### ISSUE TITLE
Guest user and internal user create request form changes 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#173]
- [x] request date and time should not be mandatory in the case where the request/issue comes via call, which is the same date/time

- [ ] First have district drop down, mapped w/ city drop down. 

![Screen Shot 2020-05-01 at 19 37 04](https://user-images.githubusercontent.com/44461004/80811306-40401500-8be3-11ea-9ceb-f5a47d0ac746.jpg)

- [x] Make corrections as indicated in image:

![Screen Shot 2020-05-01 at 19 39 59](https://user-images.githubusercontent.com/44461004/80811476-98771700-8be3-11ea-8a91-e6965c6a86a5.jpg)

- [x] Include By hand button and change "Online" to "Web" button

**Comment by YujithIsura** [comment]
- [ ] Add the following fields for guest and internal request creation forms 

1. Radio button selection with title ( Rev./ Mr./ Mrs./ Ms.)
2. GN division
3. NIC Number

- [ ] Description change to Type your Grievance or Request Here

<img width="769" alt="Screen Shot 2020-05-01 at 9 45 27 PM" src="https://user-images.githubusercontent.com/42527969/80820792-31faf480-8bf5-11ea-8a10-fc4e70a7d6ef.png">

**Comment by YujithIsura** [comment]
Add the following additional advance search options 

- [ ] Search by City
- [ ] Search by Language 
- [ ] Search by Received Mode
- [ ] Search by Organization 

<img width="771" alt="Screen Shot 2020-05-01 at 9 58 44 PM" src="https://user-images.githubusercontent.com/42527969/80821760-fd883800-8bf6-11ea-86c5-abf21c4f37a3.png">

**Comment by YujithIsura** [comment]
- [ ] Add the Total Grievance count based on the search results, Next to the EXPORT AS PDF button in the Review screen

<img width="776" alt="Screen Shot 2020-05-01 at 10 00 01 PM" src="https://user-images.githubusercontent.com/42527969/80822012-7091ae80-8bf7-11ea-9e98-cfe1287515be.png">

**Comment by YujithIsura** [comment]
- [ ] Change Mode of receipt option ONLINE to WEB
- [ ] Add additional Mode of receipt option "By Hand"

- [ ] Make corrections of Ref id as indicated in the image:

<img width="776" alt="Screen Shot 2020-05-01 at 10 06 18 PM" src="https://user-images.githubusercontent.com/42527969/80822334-1d6c2b80-8bf8-11ea-8b3f-6bbd95139f64.png">

- [ ] Remove the following alert from the internal form and add more user instruction and make it prominent 

<img width="683" alt="Screen Shot 2020-05-01 at 10 10 36 PM" src="https://user-images.githubusercontent.com/42527969/80822568-9d929100-8bf8-11ea-905c-4d4042140679.png">

**Comment by YujithIsura** [comment]
- [ ] Make the changes for main page table with the following color clarification based on the status 
1. In progress - Green
2. Completed - Gray 
3. closed - Blue

<img width="761" alt="Screen Shot 2020-05-01 at 10 12 43 PM" src="https://user-images.githubusercontent.com/42527969/80823091-8bfdb900-8bf9-11ea-9c5b-0202def5a8a2.png">

**Comment by YujithIsura** [comment]
- [ ] Create a new CSV export option for mail merge

**Comment by YujithIsura** [comment]
- [ ] Add Radio button selection with language ( Sinhala/ Tamil/ English ) for guest form and internal form 

- [ ] Change the form language based on the selection 

- [ ] Save selected language in the database for further usage (Language filter)

**Comment by MrClemRkz** [comment]
@YujithIsura backend done for Reporter and Recipient with missing fields and Incident with language field.

**Comment by MrClemRkz** [comment]
> * [x]  Change Mode of receipt option ONLINE to WEB
> * [x]  Add additional Mode of receipt option "By Hand"
> * [x]  Make corrections of Ref id as indicated in the image:
> 
> <img alt="Screen Shot 2020-05-01 at 10 06 18 PM" width="776" src="https://user-images.githubusercontent.com/42527969/80822334-1d6c2b80-8bf8-11ea-8b3f-6bbd95139f64.png">
> 

both backend and frontend done for the above.

**Comment by MrClemRkz** [comment]
>
> * [ ]  First have district drop down, mapped w/ city drop down.
> 

#221

**Comment by MrClemRkz** [comment]
closing this while having issues created to all tasks not completed.
