### ISSUE TITLE
Grafana Dashboard 

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#176]
- [ ] Create dashboard items as indicated in image:

<img width="761" alt="Screen Shot 2020-05-01 at 10 27 08 PM" src="https://user-images.githubusercontent.com/42527969/80823926-1a266f00-8bfb-11ea-85f6-61e9ea3d307f.png">

**Comment by nshamit** [comment]
New 
Verified
Action Pending 
Assigned 
In Progress

**Comment by MrClemRkz** [comment]
completed
