### ISSUE TITLE
System notifications - backend

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#19]
Develop end-points for following notifications
-internal organization notifications when requests are delegated to another.

**Comment by ManZzup** [comment]
Notifications added

* Run migrations to add notification table
* Frontend integration

- A websocket connection must be initialized using following URL
`ws://127.0.0.1:8000/ws/notifications?token=TOKEN`

Where `TOKEN` is the JWT token from auth but without the JWT part

- This would continuously push new notifications on the following format

```json
{
 "type": "notification",
  "payload": {
    "id": "3f7ef8cb-aa00-4b9a-b132-c4fc7f44ff6c",
    "notification_type": "INCIDENT_ASSIGNED",
    "is_read": false,
    "send_to": 4,
    "actioned_by": 4,
    "incident": "026d5606-bc0a-448c-972e-e04f2295ecdf",
    "custom_messsage": null,
    "createdDate": "2020-04-15T20:17:11.124665+05:30"
  }
}
```
- Apart from above two HTTP endpoints exist
- To get all notifications for a user
`GET http://127.0.0.1:8000/notifications`

- To mark a notification as read
`GET http://127.0.0.1:8000/notifications/<notification_id>/read`

**Comment by MrClemRkz** [comment]
awesome.
