### ISSUE TITLE
Advanced search UI changes:

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#26]
**Advanced search UI Changes:**
**Keep:** 
Status
1. New/Unverified
2. Verified
3. Action Pending

Priority - High/Low/Medium
Change categories
Start Date/Time and End Date/Time
Organization 
Add Sort Ascending/ Descending Order

**Remove** 
Final resolution

**Comment by YujithIsura** [comment]
Need to fix backend issues for this

**Comment by MrClemRkz** [comment]
complete on PR #51
