### ISSUE TITLE
Absence of Session Expiration

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#265]
Automatic session time outs are not evident in the current application. Instead manual session time out is available via the ‘Logout’ link.

Recommendations
- A web application should invalidate a session after a predefined idle time.

**Comment by MrClemRkz** [comment]
@YujithIsura when this is fixed, it brings up to the issue #271 where the session is expired, it gives 401 unauthorized error response from Backend API, therefore on frontend it brings the error "map is not a fucntion"

**Comment by umayangag** [comment]
- [ ] save unsubmitted work into cookies before session expire

**Comment by MrClemRkz** [comment]
> * [ ]  save unsubmitted work into cookies before session expire

this is considered as insecure. therefore will not proceed with it.

**Comment by MrClemRkz** [comment]
completed and tested. 

- frontend session out is when idle for 15 minutes.
- backend session is expired on every 20 minutes. Therefore every 15 minutes new session is aquired by 'refresh token' facility from frontend.
