### ISSUE TITLE
Insecure CORS Configuration

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#267]
The Cross-Origin Resource Sharing is not configured properly.
 
Recommendations
- Ensure that URLs responding with Access-Control-Allow-Origin: * do not include any sensitive content or information that might aid attacker in further attacks.  									 									 - Allow only selected, trusted domains in the Access-Control-Allow-Origin header. Prefer whitelisting domains over blacklisting or allowing any domain (do not use * wildcard nor blindly return the Origin header content without any checks).

**Comment by MrClemRkz** [comment]
handled from backend response

**Comment by MrClemRkz** [comment]
fixed and tested.
