### ISSUE TITLE
Vulnerable to Click Jacking

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#268]
The website is vulnerable to click jacking attacks as demonstrated below.

### Description / Vulnerability
This is when an attacker uses multiple transparent or opaque layers to trick a user into clicking on a button or link on another page when they were intending to click on the top-level page. Thus, the attacker is "hijacking" clicks meant for their page and routing them to another page, most likely owned by another application, domain, or both.

<img width="521" alt="Screen Shot 2020-05-21 at 2 37 29 PM" src="https://user-images.githubusercontent.com/42527969/82543051-a085ff00-9b70-11ea-83b0-e9995241f3ca.png">

### Recommendations
- Send the proper X-Frame-Options HTTP response headers that instruct the browser to not allow framing from other domains.  									 									 -  Employ defensive code in the UI to ensure that the current frame is the most top-level window.

**Comment by kosalag** [comment]
Add header set x-frame-options DENY to .htaccess

**Comment by MrClemRkz** [comment]
fixed for both frontend and backend admin.
