### ISSUE TITLE
Password Auto Complete Is Not Disabled

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#269]
It was observed that web form contains the password field with autocomplete enabled.

<img width="521" alt="Screen Shot 2020-05-21 at 2 42 22 PM" src="https://user-images.githubusercontent.com/42527969/82543530-505b6c80-9b71-11ea-86d1-8a0499ad6821.png">

**Comment by MrClemRkz** [comment]
code update is complete. yet browser compatibility issue will not make the fix avaliable all times. 
referece: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Browser_compatibility
