### ISSUE TITLE
Server Version Disclosed To Public

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#270]
The server version has been disclosed as shown below in server response.

<img width="382" alt="Screen Shot 2020-05-21 at 2 44 43 PM" src="https://user-images.githubusercontent.com/42527969/82543738-a6c8ab00-9b71-11ea-999b-ee68b8442165.png">

#### Recommendations
-  Hide server version and software version being displayed on application response.  									 									 -  Update the all third-party software to the latest stable version.

**Comment by MrClemRkz** [comment]
tested and complete.

**Comment by kosalag** [comment]
Add annonation to ingress
nginx.ingress.kubernetes.io/server-snippet: |
   server_tokens off;
