### ISSUE TITLE
Ageing reports

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#28]
Reports:

- [x] 1. how many requests closed by category per week
- [x] 2. how many requests closed per week by organization / dept
- [x] 3. by category (total requests) for selected period of time
- [ ] 4. delegated to each organization / dept (total requests) per week for selected period of time
- [x] 5. by category wise daily summery report

**Comment by YujithIsura** [comment]
This issue separated to issue #39 #40 #41 #42 #43
