### ISSUE TITLE
Categories displayed need to be checked again 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#285]
![Screen Shot 2020-05-28 at 10 45 23](https://user-images.githubusercontent.com/44461004/83101690-8a2bf600-a0d0-11ea-8ee6-11aadedc523a.jpg)

Here, the last category says covid 19 related problems - should it say "Other covid 19 related problems". 

Let's make sure the content makes sense

**Comment by MrClemRkz** [comment]
- removed 'rejected' top cagetory.
- updated 'covid19' sub categories.

completed and tested.
