### ISSUE TITLE
SMS notifications - To citizen 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#33]
- [x] **When issue has been submitted**
Your request has been received and is being attended to
+ Link and Ref ID

- [x] **When issue requires info**
Your request requires further information to proceed
+ Link and Ref ID

- [x]  **When issue is closed**
Your request has been resolved + Link and Ref ID. 

When link is clicked, the message should say:
Your request has been resolved + Link and Ref ID. 
Action Taken: lorem ipsum dolor.

**Comment by MrClemRkz** [comment]
tested and merged.
