### ISSUE TITLE
RefId checkup

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#53]
- [x] backend
- [x] frontend

List of things need to be completed

- Create a separate interface for the user to enter their ref id 
- upon submit will show below outputs underneath

show outputs
1) Your request is currently being attended to. 
2) your request has been received 
3) Your request has been acknowledged  
4) Your request requires further information in order to be attended to. Please click on the following link and complete the information requested. 
5) Your request has been actioned and closed.  (Get user remarks)

**Comment by MrClemRkz** [comment]
what's left to be done:
- Your request requires further information in order to be attended to. Please click on the following link and complete the information requested.
- Your request has been actioned and closed. (Get user remarks)

**Comment by MrClemRkz** [comment]
moved undone ones to #108
