### ISSUE TITLE
UI changes - Create request 

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#6]
List of things need to be completed for request guest and for internal user loggings 

- [x] Remove type of request e.g. complaint or inquiry
- [x] Remove Title
- [x] Change mode of receipt
       - Phone
       - Web app
       - Mobile app
       - Email 
       - Letter
       - Social media 
       - Fax 
       - Other
- [x] Severity - High, Low, Medium
- [x] Description - Box 
- [x] Remove occurrence
- [x] Remove election
- [x] Change category list
- [x] Note on file size and type 
- [x] Change Report information to Contact information
- [x] Change Reporter Type to Individual/Organization
- [x] Remove political affiliation 
- [x] Reporter Mobile to Mobile No.
- [x] Reporter Email to Email 
- [x] Remove check box sharing details with external parties
- [x] Location information
       - Address
       - Keep City, District, GN
       - Remove polling division, polling station, police division, police station
       - Change locations description to Additional Information (e.g. landmarks) 
- [x] Remove police-related information
- [ ] Include a legend which provides information on what the category means/includes
- [x] set mandatory fields with asterisks (*) and polish up UI (spelling/grammar)
- [ ] Add another field for main categories before the subcategories 
- [ ] Change category to sub category
- [ ] upon selecting main categories will load the related subcategories to sub category field where each subcategory name will have the main category as a prefix

**Comment by MrClemRkz** [comment]
@YujithIsura make 'reporter address' and 'location address' as multi-lined.

**Comment by YujithIsura** [comment]
noted

**Comment by nshamit** [comment]
@YujithIsura @MrClemRkz - 
we need to enable this scenario - the person complaining/ making a request on behalf of someone else. 

Process:
- Requestor inputs their name, address, contact information
- Clicks a box/radio buttons selecting that it is "on behalf of person(s)" someone else 
- Requestor inputs the name, address, contact info of the "Recipient" or "Beneficiary"

**Comment by YujithIsura** [comment]
acknowledged

**Comment by MrClemRkz** [comment]
> @YujithIsura @MrClemRkz -
> we need to enable this scenario - the person complaining/ making a request on behalf of someone else.
> 
> Process:
> 
> * Requestor inputs their name, address, contact information
> * Clicks a box/radio buttons selecting that it is "on behalf of person(s)" someone else
> * Requestor inputs the name, address, contact info of the "Recipient" or "Beneficiary"
> * State relationship to the requestor e.g. family member, acquaintance

closing the issue while creating a new issue for the above and will be on 2nd phase where user will be logged in.
