### ISSUE TITLE
UI changes - Review 

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#7]
List of things need to be completed

- [x] Search bar text - change to Search text/ Reference ID
- [x] update table columns of each review search page

**Comment by MrClemRkz** [comment]
@yujith 
- [ ] as we do not encorage getting title input, will leave description with first few 10 words/ 20 characters (ending with '...')
- [ ] will have the coulmn for category

**Comment by MrClemRkz** [comment]
completed.
