### ISSUE TITLE
UI changes for registered users 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#73]
**Home Screen** 
- [x] Change from Incidents Assigned to You to Assigned to You
- [x] Change from Incidents Linked to You to Linked to You
- [x] Status, Severity and response time - not aligned with the column titles 

![Screen Shot 2020-04-20 at 12 17 17](https://user-images.githubusercontent.com/44461004/79721986-e72dd280-8300-11ea-946a-538ce7d15714.jpg)

**Create Screen** 
- [x] There are two asterisks near mode of receipt. Please include only one asterisk

- [x] Remove mode of receipt as follows: 1) Tell Commission 2) Mobile app 3)Mobile patrolling units, 4) Civil society 5) SMS 6) Web 7) Social media 

- [x] Put asterisk near Description to show that it is mandatory 

![Screen Shot 2020-04-20 at 12 22 48](https://user-images.githubusercontent.com/44461004/79722511-cf0a8300-8301-11ea-9c49-6d648c725da0.jpg)

- [x] Change Time to Request time

- [x] Change Date to Request date

- [x] Make mandatory, using asterisk 1) Reporter Name, Indiv/Org, Address, City, District 

- [x] Include space for Secondary contact number / Landline if there is validation on the Mobile number space to allow for a landline number

**Comment by nshamit** [comment]
**Registered users  - Single incident screen** 

- [ ] Change from "Assign incident" to "Assign"

- [ ] Change from "Close incident" to "Close"

- [ ] Change from "Invalidate incident" to "Invalidate"

- [ ] Change from "incident resolution" slider button in main update section to "Resolution"

- [ ] Change from "manager eclk created the incident (12:30 PM 2020-04-20)" to manager eclk created this record" 

- [ ] Similarly, change these status messages - "manager eclk edited incident information (12:35 PM 2020-04-20)" to "manager eclk edited this record"

**Comment by nshamit** [comment]
**Verify this incident** 

![Screen Shot 2020-04-20 at 13 05 11](https://user-images.githubusercontent.com/44461004/79726021-c3ba5600-8307-11ea-8cbb-df5efa095cdd.jpg)

- [ ] Change to "Verify this record" 

- [ ] Change tick box text from "verified w/ proof" to "Verified w/ proof" - needs a capital. Otherwise, it looks like a kid has made a grammar mistake.

**Comment by nshamit** [comment]
**Review Screen** 

![Screen Shot 2020-04-20 at 13 10 30](https://user-images.githubusercontent.com/44461004/79726639-bfdb0380-8308-11ea-91ab-82f920e32ece.jpg)

- [ ] Change from "Review Complaints" to "Review"

- [ ] Change from "Search text/Incident Id" to "Search text/Reference ID"

- [ ] Advanced Search -> reorder priority to High, Medium, Low

![Screen Shot 2020-04-20 at 13 15 37](https://user-images.githubusercontent.com/44461004/79726855-13e5e800-8309-11ea-8f04-c796037787dd.jpg)

- [ ] Categories need to be updated - there is a duplicate, AND capitalized

![Screen Shot 2020-04-20 at 13 16 55](https://user-images.githubusercontent.com/44461004/79726975-468fe080-8309-11ea-9897-9193f08b8880.jpg)

- [ ] Advanced Search - why do we need to type in District Name. This should be a drop-down. 

- No Alignment of columns and text 
![Screen Shot 2020-04-20 at 13 18 25](https://user-images.githubusercontent.com/44461004/79727093-75a65200-8309-11ea-9dc5-49d54a305939.jpg)

**Comment by nshamit** [comment]
**Reports** 

- [ ] Daily Summary Report by Category

- [ ] Weekly Summary Report - Closed Requests by Category

- [ ] Weekly Summary Report - Closed Requests by Organization

**Comment by nshamit** [comment]
**Daily Summary Report by Category**
![Screen Shot 2020-04-20 at 13 30 05](https://user-images.githubusercontent.com/44461004/79728153-177a6e80-830b-11ea-9df1-ebd41a6d8e63.jpg)

- [ ] Change from "Complaints 24 hour summery (Presidential Complaints Management Centre"
to Daily Summary report by Category

- [ ] Delete පැ වකරණය / ைறபா வைகபா / Complaint classification - we don't need this row. 

- [ ] Change from "Complaints category" to "Category"

- [ ] Change from "Complaints subcategory" to Subcategory"

- [ ] Change from "Counts" to "Number"

**Comment by nshamit** [comment]
**Archive** 

![Screen Shot 2020-04-20 at 13 37 20](https://user-images.githubusercontent.com/44461004/79728798-18f86680-830c-11ea-8b56-cf180f6c3003.jpg)


- [ ] Remove all references to placeholder text and this text: eclk.incident.management.home.incidents.list.refid

**Comment by nshamit** [comment]
Error messages all refer to incidents - please change this @MrClemRkz

**Comment by nshamit** [comment]
- [ ] Make changes to category list https://github.com/LSFLK/request-management/issues/10#issuecomment-613823601

**Comment by nshamit** [comment]
- [ ] Remove mode of receipt as follows: 1) Tell Commission 2) Mobile app 3)Mobile patrolling units, 4) Civil society 5) SMS 6) Web 7) Social media

- [ ] Change Description to "Issue/ Request details" 

- [ ] Include city, district and GN division drop downs in Contact information. Remove section on location information.

**Comment by nshamit** [comment]
**Review Screen - Edit a record** 

- [ ] Should not be able to edit the following fields:
- Mode of receipt
- Description 
- Request date and time 
- Reporter Name 
- Individual /Org
- Address

**Comment by nshamit** [comment]
**Summary report by category filter by time** 

![Screen Shot 2020-04-21 at 15 38 09](https://user-images.githubusercontent.com/44461004/79853799-24b85b80-83e6-11ea-9d22-c135db4f9cdd.jpg)

- [ ] 

- [ ]  Delete පැ වකරණය / ைறபா வைகபா / Complaint classification - we don't need this row.

- [ ] Change from "Complaints category" to "Category"

- [ ] Change from "Complaints subcategory" to Subcategory"

- [ ]  Change from "Counts" to "Number"

- [ ] Change from "Complaints 24 hour summery (Presidential Complaints Management Centre"
to "Daily Summary report by Category". Check spelling of summary. 

- [ ] Remove Presidential Complaints Management Centre.

- [ ] Remove date undefined on the report or ensure that the time period can be shown properly

**Comment by nshamit** [comment]
**Weekly summary report - close requests by category**

**Comment by MrClemRkz** [comment]
alignment changes are not very neatly done. will consume big effort and time, therefore will need a separate issue.
