### ISSUE TITLE
UI changes - Incidents Assigned to you

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#8]
List of things need to be completed 

- [x] Remove description, category, last action at 
- [x] Keep Ref ID, Title, Status, response time
- [x] Change severity to priority

**Comment by MrClemRkz** [comment]
@YujithIsura 
- [ ] title to description with 20 characters.
- [ ] may be width of the table properly set for better UI on both 'Complaints Assigned to You' and 'Complaints Linked to You'

**Comment by MrClemRkz** [comment]
completed.
