### ISSUE TITLE
Guest user - can't move on and attach files in the create request form 

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#84]
![Screen Shot 2020-04-21 at 12 30 25](https://user-images.githubusercontent.com/44461004/79835453-60462c00-83cc-11ea-913e-c24e921a8958.jpg)

- [x] Cannot move on after typing in the details, including date/time and go to the next step which is attach files. The user needs to be able to enter the mandatory details and then attach files, and submit. 

- [x] Attaching files needs to be optional 

- [x] Command should be Submit not Post or Next

**Comment by MrClemRkz** [comment]
completed.
