### ISSUE TITLE
UI changes - Single incident page

### ISSUE THREAD

**Issue by YujithIsura** [LSFLK/request-management#9]
List of things need to be completed 

- [x] Change 4 tabs to 3 tabs - basic information, contact information and location information
- [x] Change complaint ref id to Reference ID
- [x] Remove Election information 
- [x] Edit - show disabled fields for fields you cannot edit
- [x] Remove escalate

**Comment by nshamit** [comment]
@MrClemRkz @YujithIsura do we need to show the tabs at all? 
If we are going to make the design responsive, we shouldn't have tabs - we should just make everything scrollable.

**Comment by YujithIsura** [comment]
@nshamit do we need this interface to be responsive, it will take a longer time to do that. I suggest if we could keep this as it is for phase 1 and for phase 2
