### ISSUE TITLE
Guest user - Check reference ID message asks us to wait for email updates when they have not provided an email

### ISSUE THREAD

**Issue by nshamit** [LSFLK/request-management#94]
When i input an ID of a record which does not have an email address logged, the status message says "...Please await updates on email". 

This message should be generic, for example, your request has been received and is being attended to. 

Messages can have the following statuses

- [x] **When issue has been submitted**
Your request has been received and is being attended to

- [x] **When issue requires info**
Your request requires further information to proceed

- [x] **When issue is closed**
Your request has been resolved and closed.
Action Taken:

**Comment by MrClemRkz** [comment]
completed.
